/* ============================================================================
   Harley's Handmade — the card-checkout bridge.  POST /api/checkout

   The only server-side code on this site, and it exists for exactly one
   reason: Square's Checkout API needs a secret token, and a secret cannot
   live in the page source of a public repo. This function reads the token
   from Cloudflare's environment BY NAME, builds a Square-hosted checkout
   from the customer's cart, and hands back the URL. No card number, no
   payment, no customer detail ever touches this code — Square hosts the
   pay page end to end (board precedent P-006 is about being IN the payment
   path; this stays out of it).

   Secrets, set in Cloudflare Pages → Settings → Variables and secrets:
     SQUARE_ACCESS_TOKEN   production token (Secret)  — never in this repo
     SQUARE_LOCATION_ID    production location (plain)
     SQUARE_SANDBOX_TOKEN  sandbox token (Secret)     — fake-card testing

   Which environment: the apex host (harleyshandmade.pages.dev, and the real
   domain when it exists) talks to real Square; every preview deployment
   (<anything>.harleyshandmade.pages.dev) and localhost talks to the SANDBOX,
   so a test on a preview branch can never charge a real card by accident.

   Price validation — bounds, not perfect recomputation, and on purpose:
   the option labels in a cart key are generated by build-products.py and
   WILL drift over time; a server that re-derives every label rejects an
   honest cart the day a label changes, and a falsely rejected cart is a
   lost sale. The floor is the strict part (nobody buys a $75 swing for a
   penny by editing the POST); the ceiling is sanity. Harley reads every
   order before he builds anything — he is the final validator, and the
   itemised order lands in his Square dashboard with the payment.

   The quoted rule is enforced HERE as well as in the page: anything Harley
   has not put a number on is never card-charged. A cart carrying quoted
   extras gets a 400, whatever the client claimed.
   ========================================================================== */

/* Exact data-name / data-n strings from the built pages. If a product is
   renamed in build-products.py, rename it here in the same commit. */
const PRODUCTS = {
  'Mini Porch Swing':        { base: 75  },
  'Loveseat Swing':          { base: 75  },
  /* Added 2026-08-29 — Harley's 2026-08-25 emails: the stand became its own
     product (the With Stand option is retired, see the guard below), and the
     four fall pieces are his "1 of 4" through "4 of 4", his prices. */
  'Mini Swing Stand':        { base: 25  },
  'Picnic Table Feeder':     { base: 75  },
  'Adirondack Chair Feeder': { base: 75  },
  'Birdhouse':               { base: 150 },
  'Fall Sign Block — Cherry · Porch Season':                            { base: 25 },
  'Fall Sign Block — Black Walnut · Sweater Weather & Bourbon':         { base: 25 },
  'Fall Plaque — Black Walnut · Boots, Bourbon & Bonfires':             { base: 50 },
  'Fall Plaque — Black Walnut · Leaves Are Falling, Bourbon\'s Calling': { base: 50 },
  /* ⛔ REMOVED 2026-07-31 — Engraved Sign ($285), Hand-Carved Cardinal ($425)
     and Custom Picture Frame ($145–205). Jeff retired all three to quoted
     custom work the same day: they need too much per-piece adjustment to carry
     a shelf price. Leaving them here let the server mint a REAL payment link
     for an engraved sign at $285 — charging a card for a piece Harley is
     supposed to price after seeing it, which is the exact thing this file
     exists to prevent. Caught by the audit, not by the UI, because the UI
     cannot produce those keys any more.
     ⚠️ It was NOT unreachable: a cart is localStorage, so anyone who added one
     of these before today still has it, and their next "Pay with card" would
     have gone through. Now it is refused and they are told to refresh — the
     send-the-order button sits right beside it.
     If any of the three ever returns to the shelf, it comes back HERE and in
     build-products.py's P list together. */
};

/* Ceiling above base: stain (+15/+25) + stand (+20) + frame size (+60) all
   fit under this with room; anything higher is a tampered or broken cart. */
const MAX_ADDS = 150;

/* ── PER-ITEM SHIPPING, IN CENTS — the AUTHORITATIVE table ────────────────
   Jeff, 2026-08-06: "the shipping on every item in the shop will be different
   so all flat rate shipping price is not going to work, each item will have
   its own shipping price." Harley's own figures.

   Supersedes the flat $23 (2026-07-31), which was overcharging most of the
   catalogue by more than double — a $10 chair feeder billed $23 postage on a
   live store that had already taken real orders.

   `stand` is the rate when the customer picks the matching cedar A-frame
   stand: a second, bigger parcel. Only the two swings offer it.

   ⚠️ THIS IS THE NUMBER THE CUSTOMER IS ACTUALLY CHARGED. The browser's copy
   lives in assets/ship-rates.js (generated by build-products.py) and is for
   DISPLAY ONLY — this file must never take a postage figure from a request
   body, for the same reason it re-prices every line instead of trusting `p`.
   Two copies on purpose; build-products.py's SHIP dict is the source the
   other is generated from. Change them together.

   The old flat rate lived in FOUR places and a rate rise missed one of them
   (the note further down records a customer shown $18 and charged $23).
   Two deliberate copies beat four accidental ones. */
const SHIP_CENTS = {
  'Mini Porch Swing':        { base: 1000 },
  'Loveseat Swing':          { base: 1000 },
  'Mini Swing Stand':        { base: 800 },
  'Picnic Table Feeder':     { base: 1000 },
  'Adirondack Chair Feeder': { base: 1000 },
  'Birdhouse':               { base: 2400 },
  'Fall Sign Block — Cherry · Porch Season':                            { base: 800 },
  'Fall Sign Block — Black Walnut · Sweater Weather & Bourbon':         { base: 800 },
  'Fall Plaque — Black Walnut · Boots, Bourbon & Bonfires':             { base: 1000 },
  'Fall Plaque — Black Walnut · Leaves Are Falling, Bourbon\'s Calling': { base: 1000 },
};
/* ⛔ The stand:1800 rates are GONE (2026-08-29). Harley, 2026-08-25: the
   stand is its own product now — swing $10 + stand $8 is the same $18 the
   old with-stand rate charged, priced honestly per parcel. */

/* The exact option label the RETIRED stand radio wrote into cart keys. A
   cart is localStorage, so a line added before 2026-08-29 can still carry
   it — those lines are refused plainly below rather than priced by guess. */
const STAND_LABEL = 'Matching cedar stand';

function shipCentsFor(name) {
  const r = SHIP_CENTS[name];
  return r ? r.base : null;
}
const MAX_LINES = 12, MAX_QTY = 25, MAX_TOTAL_CENTS = 500000; // $5,000

const SUPPORT_EMAIL = 'harley@harleyshandmadeky.com';

function json(status, obj) {
  return new Response(JSON.stringify(obj), {
    status: status,
    headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' },
  });
}

/* Sandbox for every host except the apex + the real domain. Note the leading
   dot: the apex itself does NOT end with ".harleyshandmade.pages.dev". */
function isSandboxHost(host) {
  return host.endsWith('.harleyshandmade.pages.dev')
      || host === 'localhost' || host.startsWith('localhost:')
      || host === '127.0.0.1' || host.startsWith('127.0.0.1:');
}

/* Resolved per environment and cached for the isolate's life. */
const locationCache = {};

/* The configured ID is a string a human copied out of a dashboard, and the
   first production probe proved that assumption wrong: Square returned
   INVALID_VALUE (400) — token fine, location rejected. So the token, which
   is the thing that cannot be mistyped without failing loudly, is used to
   ask Square which locations actually exist. A configured ID that checks
   out is honoured; anything else falls back to the active location rather
   than failing a customer's checkout over a typo. */
async function resolveLocation(api, token, configured, envKey) {
  if (locationCache[envKey]) return locationCache[envKey];
  const r = await fetch(api + '/v2/locations', { headers: { Authorization: 'Bearer ' + token } });
  const j = await r.json().catch(() => null);
  const locs = (j && j.locations) || [];
  if (!locs.length) return null;
  const match = configured && locs.find(l => l.id === configured);
  const chosen = match || locs.find(l => l.status === 'ACTIVE') || locs[0];
  if (!match && configured) {
    console.warn('SQUARE_LOCATION_ID', configured, 'is not a location on this account;',
      'falling back to', chosen.id, '(' + (chosen.name || 'unnamed') + ').',
      'Locations available:', locs.length);
  }
  locationCache[envKey] = chosen.id;
  return chosen.id;
}

export async function onRequestPost(context) {
  const req = context.request, env = context.env;
  const url = new URL(req.url);
  const sandbox = isSandboxHost(url.hostname);

  const token = sandbox ? env.SQUARE_SANDBOX_TOKEN : env.SQUARE_ACCESS_TOKEN;
  const api = sandbox ? 'https://connect.squareupsandbox.com' : 'https://connect.squareup.com';
  if (!token) {
    /* Self-diagnosing on purpose: if Jeff only filled the Production
       environment in Cloudflare, this is the message that says so. */
    return json(503, { error: (sandbox ? 'SQUARE_SANDBOX_TOKEN' : 'SQUARE_ACCESS_TOKEN')
      + ' is not set for this environment in Cloudflare Pages → Variables and secrets.' });
  }

  let body;
  try { body = await req.json(); } catch (e) { return json(400, { error: 'Bad request body.' }); }

  const lines = Array.isArray(body && body.lines) ? body.lines : null;
  if (!lines || !lines.length || lines.length > MAX_LINES)
    return json(400, { error: 'The cart looks empty or malformed — refresh the shop page and try again.' });

  const shipping = body.fulfillment === 'ship';
  if (!shipping && body.fulfillment !== 'pickup')
    return json(400, { error: 'Pick pickup or shipping before paying.' });

  /* Pickup slot (2026-08-29 — the Marathon-station pickup flow, Harley's
     2026-08-25 email: order at least 3 days ahead and pick a time). The cart
     requires it before Pay; here it is OPTIONAL on purpose — Cloudflare
     serves cart.js at max-age=14400, so for up to four hours after deploy a
     cached cart can still POST without the field, and a hard requirement
     would fail those checkouts (P-012's cache window, server-side). Format
     is validated, not trusted: it goes into the payment note Harley reads. */
  let pickupWhen = '';
  if (!shipping && body.pickup && typeof body.pickup === 'object') {
    const d = String(body.pickup.date || '').slice(0, 10);
    const t = String(body.pickup.time || '').slice(0, 5);
    if (/^\d{4}-\d{2}-\d{2}$/.test(d))
      pickupWhen = d + (/^\d{1,2}:\d{2}$/.test(t) ? ' at ' + t : '');
  }

  const items = [];
  const parsed = [];
  /* hoisted: the payment note below needs it outside the shipping branch */
  let shipCents = 0;
  let totalCents = 0;
  for (const ln of lines) {
    if (!ln || typeof ln.key !== 'string' || ln.key.length > 300)
      return json(400, { error: 'Cart line malformed — refresh and try again.' });
    if (ln.quoted && ln.quoted.length)
      return json(400, { error: 'Part of this order needs Harley’s eyes before it has a price — send him the order instead of paying now.' });

    const m = ln.key.match(/^(.*?)(?:\s*\((.*)\))?$/);
    const name = (m && m[1] || '').trim(), opts = (m && m[2] || '').trim();
    const prod = PRODUCTS[name];
    if (!prod) return json(400, { error: '"' + name + '" isn’t a product this shop sells — refresh the shop page.' });

    /* The With Stand option came off the swings on 2026-08-29 (Harley's
       email — the stand is its own $25 product now). A cart is localStorage,
       so a line added before that day can still carry the old option; it no
       longer has a postage rate or a current price, so refuse it plainly
       instead of guessing. The customer is told exactly what to do. */
    if (opts.indexOf(STAND_LABEL) !== -1)
      return json(400, { error: 'The swing stand is its own product now — remove this line, refresh the shop, and add the swing and the Mini Swing Stand ($25) separately.' });

    const q = ln.q, p = ln.p;
    if (!Number.isInteger(q) || q < 1 || q > MAX_QTY) return json(400, { error: 'Quantity out of range.' });
    if (typeof p !== 'number' || !isFinite(p) || p < prod.base || p > prod.base + MAX_ADDS)
      return json(400, { error: 'A price in the cart doesn’t match the shop — refresh the page and rebuild the order.' });

    const cents = Math.round(p * 100);
    totalCents += cents * q;
    /* Remember what this line IS, so postage can be priced from the product
       and its chosen option rather than from one number for the whole cart. */
    parsed.push({ name: name, opts: opts, q: q });
    items.push({
      name: name,
      quantity: String(q),
      base_price_money: { amount: cents, currency: 'USD' },
      note: opts ? opts.slice(0, 500) : undefined,
    });
  }
  if (shipping) {
    /* PER PACKAGE, not per order (Jeff, 2026-07-31: "the shipping rate in
       checkout stays the same no matter how many items are added, that needs
       to be a per item charge"). These are bulky wooden pieces — a porch swing
       and a birdhouse do not share a box — so every item is its own parcel and
       its own label. Two swings is two boxes and two lots of postage; charging
       one $23 for both had Harley paying the second label himself.

       A line item, not a service charge, for two reasons: it shows on the
       receipt in the customer's own words, and the order-level KY tax applies
       to it automatically — which Kentucky requires. Delivery, postage,
       handling and packaging are all inside "sales price" under KRS 139.010,
       so shipping on a taxable good is taxable. Leaving it untaxed would have
       Harley under-collecting and owing it on audit. */
    const parcels = parsed.reduce((n, ln) => n + ln.q, 0);

    /* Priced per LINE now: each line's own rate (and its stand option, which
       is a second parcel) times its quantity. A swing on rope and a birdhouse
       in one order are $10 and $24 — not two of anything. */
    for (const ln of parsed) {
      const rate = shipCentsFor(ln.name);
      if (rate === null)
        return json(400, { error: 'Shipping is not set for "' + ln.name
          + '" — send Harley the order and he will price the postage himself.' });
      shipCents += rate * ln.q;
    }

    /* ONE line item carrying the summed postage, quantity 1. It used to be
       quantity=parcels at a single unit rate, which only worked while every
       item cost the same to send. Per-item rates cannot be expressed that way,
       and Square would print a unit price that is true of nothing in the box.
       Still a line item rather than a service charge, so the order-level KY
       tax applies to it — delivery, postage, handling and packaging are all
       inside "sales price" under KRS 139.010. */
    items.push({
      name: 'Shipping',
      quantity: '1',
      base_price_money: { amount: shipCents, currency: 'USD' },
      note: parcels === 1
        ? 'One package, anywhere in the US'
        : parcels + ' packages, priced per item, anywhere in the US',
    });
    totalCents += shipCents;
  }

  if (totalCents < 100 || totalCents > MAX_TOTAL_CENTS)
    return json(400, { error: 'Order total out of range.' });

  /* Same path for both environments — the token decides which account we
     are talking to, and Square decides which locations are real. */
  const locationId = await resolveLocation(
    api, token, sandbox ? null : env.SQUARE_LOCATION_ID, sandbox ? 'sandbox' : 'prod');
  if (!locationId) return json(502, { error: 'This Square account has no location to sell from.' });

  const sq = await fetch(api + '/v2/online-checkout/payment-links', {
    method: 'POST',
    headers: { Authorization: 'Bearer ' + token, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      idempotency_key: crypto.randomUUID(),
      order: {
        location_id: locationId,
        line_items: items,
        /* Jeff, 2026-07-30: "all items are + 6% sales tax." Kentucky is a
           flat statewide 6%, ADDITIVE at checkout — never buried in the item
           price — so the receipt shows the customer the same split the cart
           panel showed, and Harley's dashboard reports collected tax for his
           KY filing. The cart panel computes the identical 6% (all prices
           are whole dollars, so the cent math is exact on both sides). */
        taxes: [{ uid: 'ky-sales-tax', name: 'KY sales tax', type: 'ADDITIVE', percentage: '6', scope: 'ORDER' }],
      },
      checkout_options: {
        /* Square collects the address on its own page for shipped orders, so
           it arrives attached to the order in the dashboard — which is what
           the Create Label button reads from. Pickup orders are never asked
           for an address they don't need. */
        ask_for_shipping_address: shipping,
        merchant_support_email: SUPPORT_EMAIL,
        redirect_url: url.origin + '/thanks?paid=1',
      },
      /* DERIVED, never typed. This note said "$18" until 2026-08-04 while the
         customer was actually charged $23 — the rate rose and this fourth copy
         of it was missed, because the comment on SHIPPING_FLAT_CENTS lists only
         three places to change (here, cart.js SHIP_FLAT, the shop copy). It is
         the note Harley reads in Square at the moment he buys the label, so a
         stale number tells him he collected $5 less per package than he did.
         Building it from the constant removes the fourth copy entirely. */
      payment_note: shipping
        ? 'Website order — SHIP IT. Postage $' + (shipCents / 100).toFixed(2)
          + ' paid across ' + parsed.reduce((n, ln) => n + ln.q, 0)
          + ' package(s); buy the labels in Orders > Shipments.'
        : 'Website order — FREE PICKUP, Marathon station next to Ace Hardware, Owingsville'
          + (pickupWhen ? '. Customer picked: ' + pickupWhen
                        : '. No time chosen — arrange by reply')
          + ' (no shipping owed).',
    }),
  });

  const out = await sq.json().catch(() => null);
  if (!sq.ok || !out || !out.payment_link || !out.payment_link.url) {
    /* Full detail to the function log (Cloudflare dashboard), a calm
       sentence to the customer — the cart falls back to send-the-order.
       `code` carries Square's own error category (UNAUTHORIZED,
       INVALID_LOCATION…) — no secret material, and it is the difference
       between diagnosing this in one request and guessing at it. The cart
       never shows it; it exists for whoever is debugging. */
    console.error('Square CreatePaymentLink failed', sq.status, JSON.stringify(out));
    const e = out && out.errors && out.errors[0];
    return json(502, {
      error: 'Square didn’t accept the checkout just now.',
      code: e ? (e.code || e.category || 'UNKNOWN') : 'NO_BODY',
      field: e && e.field ? e.field : undefined,
      httpStatus: sq.status,
    });
  }
  return json(200, { url: out.payment_link.url });
}

export async function onRequest(context) {
  if (context.request.method === 'POST') return onRequestPost(context);
  return json(405, { error: 'POST only.' });
}
