/* ============================================================================
   Harley's Handmade — the card-checkout bridge.  POST /api/checkout

   The only server-side code on this site, and it exists for exactly one
   reason: Square's Checkout API needs a secret token, and a secret cannot
   live in the page source of a public repo. This function reads the token
   from Cloudflare's environment BY NAME, builds a Square-hosted checkout
   from the customer's cart, and hands back the URL. No card number, no
   payment, no customer detail ever touches this code — Square hosts the
   pay page end to end (board precedent P-006 is about being IN the payment
   path; this stays out of it).

   Secrets, set in Cloudflare Pages → Settings → Variables and secrets:
     SQUARE_ACCESS_TOKEN   production token (Secret)  — never in this repo
     SQUARE_LOCATION_ID    production location (plain)
     SQUARE_SANDBOX_TOKEN  sandbox token (Secret)     — fake-card testing

   Which environment: the apex host (harleyshandmade.pages.dev, and the real
   domain when it exists) talks to real Square; every preview deployment
   (<anything>.harleyshandmade.pages.dev) and localhost talks to the SANDBOX,
   so a test on a preview branch can never charge a real card by accident.

   Price validation — bounds, not perfect recomputation, and on purpose:
   the option labels in a cart key are generated by build-products.py and
   WILL drift over time; a server that re-derives every label rejects an
   honest cart the day a label changes, and a falsely rejected cart is a
   lost sale. The floor is the strict part (nobody buys a $75 swing for a
   penny by editing the POST); the ceiling is sanity. Harley reads every
   order before he builds anything — he is the final validator, and the
   itemised order lands in his Square dashboard with the payment.

   The quoted rule is enforced HERE as well as in the page: anything Harley
   has not put a number on is never card-charged. A cart carrying quoted
   extras gets a 400, whatever the client claimed.
   ========================================================================== */

/* Exact data-name / data-n strings from the built pages. If a product is
   renamed in build-products.py, rename it here in the same commit. */
const PRODUCTS = {
  'Mini Porch Swing':        { base: 75  },
  'Loveseat Swing':          { base: 75  },
  'Picnic Table Feeder':     { base: 75  },
  'Adirondack Chair Feeder': { base: 75  },
  'Birdhouse':               { base: 150 },
  /* Unlinked from the shop but the pages still deploy (launch decision
     pending) — a deep-linked buyer is still a buyer. */
  'Engraved Sign':           { base: 285 },
  'Hand-Carved Cardinal':    { base: 425 },
  /* The frame's base is size-interpolated $145–$205 (product.js), so its
     floor is the range floor. */
  'Custom Picture Frame':    { base: 145 },
};

/* Ceiling above base: stain (+15/+25) + stand (+20) + frame size (+60) all
   fit under this with room; anything higher is a tampered or broken cart. */
const MAX_ADDS = 150;

/* Flat shipping, in cents. Set from Harley's own figures (2026-07-30, via
   Jeff): heaviest shop item ~3 lb, $7 of packaging per order. A 3 lb Ground
   Advantage label at Square/Shippo commercial rates runs ~$8.50 nearby to
   ~$15.75 to the west coast, so his true cost is ~$15.50–$22.75. $18 covers
   packaging plus the label everywhere he is likely to ship and runs a few
   dollars short only on a far-zone order.
   ⚠️ The SERVER decides this number, never the browser — the client sends
   only its choice of pickup-or-ship. */
const SHIPPING_FLAT_CENTS = 1800;
const MAX_LINES = 12, MAX_QTY = 25, MAX_TOTAL_CENTS = 500000; // $5,000

const SUPPORT_EMAIL = 'harley@harleyshandmadeky.com';

function json(status, obj) {
  return new Response(JSON.stringify(obj), {
    status: status,
    headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' },
  });
}

/* Sandbox for every host except the apex + the real domain. Note the leading
   dot: the apex itself does NOT end with ".harleyshandmade.pages.dev". */
function isSandboxHost(host) {
  return host.endsWith('.harleyshandmade.pages.dev')
      || host === 'localhost' || host.startsWith('localhost:')
      || host === '127.0.0.1' || host.startsWith('127.0.0.1:');
}

/* Resolved per environment and cached for the isolate's life. */
const locationCache = {};

/* The configured ID is a string a human copied out of a dashboard, and the
   first production probe proved that assumption wrong: Square returned
   INVALID_VALUE (400) — token fine, location rejected. So the token, which
   is the thing that cannot be mistyped without failing loudly, is used to
   ask Square which locations actually exist. A configured ID that checks
   out is honoured; anything else falls back to the active location rather
   than failing a customer's checkout over a typo. */
async function resolveLocation(api, token, configured, envKey) {
  if (locationCache[envKey]) return locationCache[envKey];
  const r = await fetch(api + '/v2/locations', { headers: { Authorization: 'Bearer ' + token } });
  const j = await r.json().catch(() => null);
  const locs = (j && j.locations) || [];
  if (!locs.length) return null;
  const match = configured && locs.find(l => l.id === configured);
  const chosen = match || locs.find(l => l.status === 'ACTIVE') || locs[0];
  if (!match && configured) {
    console.warn('SQUARE_LOCATION_ID', configured, 'is not a location on this account;',
      'falling back to', chosen.id, '(' + (chosen.name || 'unnamed') + ').',
      'Locations available:', locs.length);
  }
  locationCache[envKey] = chosen.id;
  return chosen.id;
}

export async function onRequestPost(context) {
  const req = context.request, env = context.env;
  const url = new URL(req.url);
  const sandbox = isSandboxHost(url.hostname);

  const token = sandbox ? env.SQUARE_SANDBOX_TOKEN : env.SQUARE_ACCESS_TOKEN;
  const api = sandbox ? 'https://connect.squareupsandbox.com' : 'https://connect.squareup.com';
  if (!token) {
    /* Self-diagnosing on purpose: if Jeff only filled the Production
       environment in Cloudflare, this is the message that says so. */
    return json(503, { error: (sandbox ? 'SQUARE_SANDBOX_TOKEN' : 'SQUARE_ACCESS_TOKEN')
      + ' is not set for this environment in Cloudflare Pages → Variables and secrets.' });
  }

  let body;
  try { body = await req.json(); } catch (e) { return json(400, { error: 'Bad request body.' }); }

  const lines = Array.isArray(body && body.lines) ? body.lines : null;
  if (!lines || !lines.length || lines.length > MAX_LINES)
    return json(400, { error: 'The cart looks empty or malformed — refresh the shop page and try again.' });

  const shipping = body.fulfillment === 'ship';
  if (!shipping && body.fulfillment !== 'pickup')
    return json(400, { error: 'Pick pickup or shipping before paying.' });

  const items = [];
  let totalCents = 0;
  for (const ln of lines) {
    if (!ln || typeof ln.key !== 'string' || ln.key.length > 300)
      return json(400, { error: 'Cart line malformed — refresh and try again.' });
    if (ln.quoted && ln.quoted.length)
      return json(400, { error: 'Part of this order needs Harley’s eyes before it has a price — send him the order instead of paying now.' });

    const m = ln.key.match(/^(.*?)(?:\s*\((.*)\))?$/);
    const name = (m && m[1] || '').trim(), opts = (m && m[2] || '').trim();
    const prod = PRODUCTS[name];
    if (!prod) return json(400, { error: '"' + name + '" isn’t a product this shop sells — refresh the shop page.' });

    const q = ln.q, p = ln.p;
    if (!Number.isInteger(q) || q < 1 || q > MAX_QTY) return json(400, { error: 'Quantity out of range.' });
    if (typeof p !== 'number' || !isFinite(p) || p < prod.base || p > prod.base + MAX_ADDS)
      return json(400, { error: 'A price in the cart doesn’t match the shop — refresh the page and rebuild the order.' });

    const cents = Math.round(p * 100);
    totalCents += cents * q;
    items.push({
      name: name,
      quantity: String(q),
      base_price_money: { amount: cents, currency: 'USD' },
      note: opts ? opts.slice(0, 500) : undefined,
    });
  }
  if (shipping) {
    /* A line item, not a service charge, for two reasons: it shows on the
       receipt in the customer's own words, and the order-level KY tax
       applies to it automatically — which Kentucky requires. Delivery,
       postage, handling and packaging are all inside "sales price" under
       KRS 139.010, so shipping on a taxable good is taxable. Leaving it
       untaxed would have Harley under-collecting and owing it on audit. */
    items.push({
      name: 'Shipping',
      quantity: '1',
      base_price_money: { amount: SHIPPING_FLAT_CENTS, currency: 'USD' },
      note: 'Flat rate, anywhere in the US',
    });
    totalCents += SHIPPING_FLAT_CENTS;
  }

  if (totalCents < 100 || totalCents > MAX_TOTAL_CENTS)
    return json(400, { error: 'Order total out of range.' });

  /* Same path for both environments — the token decides which account we
     are talking to, and Square decides which locations are real. */
  const locationId = await resolveLocation(
    api, token, sandbox ? null : env.SQUARE_LOCATION_ID, sandbox ? 'sandbox' : 'prod');
  if (!locationId) return json(502, { error: 'This Square account has no location to sell from.' });

  const sq = await fetch(api + '/v2/online-checkout/payment-links', {
    method: 'POST',
    headers: { Authorization: 'Bearer ' + token, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      idempotency_key: crypto.randomUUID(),
      order: {
        location_id: locationId,
        line_items: items,
        /* Jeff, 2026-07-30: "all items are + 6% sales tax." Kentucky is a
           flat statewide 6%, ADDITIVE at checkout — never buried in the item
           price — so the receipt shows the customer the same split the cart
           panel showed, and Harley's dashboard reports collected tax for his
           KY filing. The cart panel computes the identical 6% (all prices
           are whole dollars, so the cent math is exact on both sides). */
        taxes: [{ uid: 'ky-sales-tax', name: 'KY sales tax', type: 'ADDITIVE', percentage: '6', scope: 'ORDER' }],
      },
      checkout_options: {
        /* Square collects the address on its own page for shipped orders, so
           it arrives attached to the order in the dashboard — which is what
           the Create Label button reads from. Pickup orders are never asked
           for an address they don't need. */
        ask_for_shipping_address: shipping,
        merchant_support_email: SUPPORT_EMAIL,
        redirect_url: url.origin + '/thanks?paid=1',
      },
      payment_note: shipping
        ? 'Website order — SHIP IT. Flat $18 shipping paid; buy the label in Orders > Shipments.'
        : 'Website order — FREE PICKUP arranged with the customer (no shipping owed)',
    }),
  });

  const out = await sq.json().catch(() => null);
  if (!sq.ok || !out || !out.payment_link || !out.payment_link.url) {
    /* Full detail to the function log (Cloudflare dashboard), a calm
       sentence to the customer — the cart falls back to send-the-order.
       `code` carries Square's own error category (UNAUTHORIZED,
       INVALID_LOCATION…) — no secret material, and it is the difference
       between diagnosing this in one request and guessing at it. The cart
       never shows it; it exists for whoever is debugging. */
    console.error('Square CreatePaymentLink failed', sq.status, JSON.stringify(out));
    const e = out && out.errors && out.errors[0];
    return json(502, {
      error: 'Square didn’t accept the checkout just now.',
      code: e ? (e.code || e.category || 'UNKNOWN') : 'NO_BODY',
      field: e && e.field ? e.field : undefined,
      httpStatus: sq.status,
    });
  }
  return json(200, { url: out.payment_link.url });
}

export async function onRequest(context) {
  if (context.request.method === 'POST') return onRequestPost(context);
  return json(405, { error: 'POST only.' });
}
